valor_compra = float(input("informe o valor da compra: R$"))
valor_pago = float(input("informe o valor pago pelo cliente: R$"))
troco = int(valor_pago - valor_compra)  
n100 = troco  // 100
troco = troco % 100
n50 = troco // 50
troco = troco % 50
n20 = troco // 20
troco = troco % 20
n10 = troco // 10
troco = troco % 10
n5 = troco // 5
troco = troco %5
print(f"\n\t=>  Valor Pago: R${valor_pago:.2f}")
print(f"\n\t=>Valor Compra: R${valor_compra:.2f}")
print(f"\n\t=>       Troco: R${valor_pago-valor_compra:.2f}, Sendo:")
print(f"\n\t               =>{n100: 3d} cédulas de R$100")
print(f"\n\t               =>{n50: 3d} cédulas de R$ 50")
print(f"\n\t               =>{n20: 3d} cédulas de R$ 20")
print(f"\n\t               =>{n10: 3d} cédulas de R$ 10")
print(f"\n\t               =>{n5: 3d} cédulas de R$  5")
print(f"\n\t               =>{troco: 3d} cédulas de R$  1")